```
Traceback (most recent call last):
  File "/Users/highlander/Desktop/Project-Heimir/main.py", line 5, in <module>
    from github import Github
ImportError: cannot import name 'Github' from 'github' (/Users/highlander/Desktop/Project-Heimir/venv/lib/python3.10/site-packages/github/__init__.py)
```

[https://github.com/PyGithub/PyGithub/issues/856#issuecomment-421110639](https://github.com/PyGithub/PyGithub/issues/856#issuecomment-421110639)

